version: '2'
services:
  backend:
    image: ms-ux-distribucion-de-costos-envio-parametria-pga:latest
    build:
      context: .
    volumes:
      - ./docker-files/application.yml:/opt/application.yml
    ports:
      - "9091:9091"
    depends_on:
      - db
      - redis
  db:
    image: mcmoe/mssqldocker
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mypass1.
      MSSQL_DB: 'DummyDb'
      MSSQL_USER: asmws
      MSSQL_PASSWORD: mypass1.
    ports:
      - "1433:1433"
  redis:
    image: redis
    ports:
      - "6379:6379"
